from cool_linear_solver.eqs_and_vars import Variable, Linear_equation
from cool_linear_solver.least_squares import Least_squares, Constrained_least_squares
from cool_linear_solver.linear_solver import System_of_linear_eqs